### PR TITLE
SignIn And SignUp page design initially done

### PR DESCRIPTION
**Pull request by rokyuddin**
1. Add signIn page
2. add signUp page
3. add parallal route 
4. add auth route group
5. add toaster in layout and refactor root page
6. add shadcn components

### CODE REVIEW

**Comment by zarif-tajwar** [comment]
Could you explain what purpose parallel routes serve here?

**Comment by rokyuddin** [comment]
**Parallel Routes**
Parallel Routes allows you to simultaneously or conditionally render one or more pages within the same layout. 

[https://nextjs.org/docs/app/building-your-application/routing/parallel-routes](https://nextjs.org/docs/app/building-your-application/routing/parallel-routes)

**Comment by zarif-tajwar** [comment]
Yep, I know them well! Thats why I'm confused why are they needed here. Can you elaborate what exactly are you trying to achieve with it?

**Comment by rokyuddin** [comment]
To enhance the user experience, I plan to use a modal instead of directly redirecting to the login page. Since the form only includes two buttons, implementing a modal with Next.js parallel routes will create a smoother interaction for the user. 

**Seamless Navigation**: Parallel routes allow you to show the login modal without a full page navigation, keeping the user in the current context
**Persistent State**: If the user refreshes the page while the modal is open, the modal state can be preserved, providing a smoother experience

**Comment by zarif-tajwar** [comment]
That sounds awesome! Thanks for bringing up this feature.

**Pull request merged**
